spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipeAppDb
    username: user
    password: user
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/scripts/database-create-script.sql

logging:
  level:
    org.springframework.security: DEBUG